### ISSUE TITLE
account link expiration displays wrong interval

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#429]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/184236692)    

    It seems the mijn-eduID website shows the date the account will be removed(```removal-duration-days-non-validated:```), not the date the link is invalidated (```expiry-duration-days-non-validated```).

```
linked_accounts:
  # The duration that non validated-name linked accounts are valid - note that they are not removed and will still be used for EPPN Pseudonymisation
  expiry-duration-days-non-validated: 180
  # The duration after which non validated-name linked accounts are removed
  removal-duration-days-non-validated: 540
  # The duration after which validated-name linked accounts are removed
  removal-duration-days-validated: 2190
```
