### ISSUE TITLE
Config for clients

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#490]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187561967)    

    The remote clients creating eduID\'s need to authenticate using basic auth. 
Because an eduID targetted identifier will be generated, an institution identifier is also needed.
This information will be added in the application.yml. suggestion: 
```
remoteCreation:
  - studielink:
    user: studielink
    api-password: secret
    rpclientid: rp.studielink.nl
    schachome: studielink.nl
```
